### ISSUE TITLE
service.modulpos.ru сертификат заэкспайрился

### ISSUE THREAD

**Issue by VampiRUS** [bigperson/modulpos-php-api-client#12]
Нужно baseurl на my.modulkassa.ru обновить

**Comment by re8us** [comment]
> Нужно baseurl на my.modulkassa.ru обновить

Спасибо! а то уже часа три жду новостей что делать... 
А были где-то предупреждения? Кто редиска-то?

**Comment by VampiRUS** [comment]
Вроде не было. В документации оба как равнозначные указаны. Может быть просто забыли продлить.

**Comment by bigperson** [comment]
В актуальной документации https://modulkassa.ru/fs/files/API_avtomaticheskoj_fiskalizatsii.pdf указан base url 
https://service.modulpos.ru/api/fn
или 
https://my.modulkassa.ru/api/fn

Эти уроды просрали сертификат на .modulpos.ru
