### ISSUE TITLE
Поддержка ФФД 1.05

### ISSUE THREAD

**Issue by re8us** [bigperson/modulpos-php-api-client#3]
Здравствуйте!

Планируете поддержку ФФД 1.05? 
Или не ждать?

**Comment by bigperson** [comment]
@re8us Да планируется, если дадите информацию что необходимо обновить сделаю быстрее.

Как понял надо добавить два дополнительных признака:

> paymentObject string - Предмет расчета. Список доступных значений:
● commodity
● excise
● job
● service
● gambling_bet
● gambling_prize
● lottery
● lottery_prize
● intellectual_activity
● payment
● agent_commission
● composite
● another
Если не указано, то касса проводит продажу с предметом расчета **ТОВАР**
paymentMethod string - Признак расчета. Список доступных значений:
● full_prepayment
● prepayment
● advance
● full_payment
● partial_payment
● credit
● credit_payment
Если не указано, то касса проводит продажу с признаком расчета **ПОЛНЫЙ РАСЧЕТ**


То есть по умолчанию, сейчас все должно работать.

**Comment by re8us** [comment]
Да, вроде всё верно, это для каждой позиции.

О, по поводу значений по-умолчанию на стороне кассы я не подумал, я пока оперативно наколхозил чтоб уж наверняка
<img width="931" alt="2018-12-31 18 04 42" src="https://user-images.githubusercontent.com/4831984/50561702-3f148480-0d1e-11e9-8d86-e1336a962147.png">
...

**Comment by bigperson** [comment]
@re8us Не стесняйтесь форкать и присылать пул реквест 👍

**Comment by re8us** [comment]
Да я нормально не сделаю) интерфейсы эти, эксепшены... тем более тесты...

**Comment by bigperson** [comment]
@re8us Есть повод прокачать скилл за праздники

**Comment by bigperson** [comment]
@re8us зарелизил поддержку
