### ISSUE TITLE
Отсутствует класс Cashier

### ISSUE THREAD

**Issue by liggth** [bigperson/modulpos-php-api-client#5]
При создании чека формируем инфу о продавце 
`//Создаем кассира
$cashier = Cashier::create([
    'name' => 'Test Cashier',
    'inn' => '123456789012',
    'position' => 'salesman',
]);`

но получаю ошибку: 
Fatal error: Class 'Bigperson\ModulposApiClient\Entity\Cashier' not found in... 

И действительно, отсутствует файл с данным классом

**Comment by ipolikarpov** [comment]
+

**Comment by bigperson** [comment]
Обновитесь до версии ^1.0
