### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by igortsev** [bigperson/modulpos-php-api-client#8]
Problem 1
    - Installation request for bigperson/modulpos-php-api-client dev-master -> satisfiable by bigperson/modulpos-php-api-client[dev-master].
    - Conclusion: remove symfony/event-dispatcher v4.2.4
    - Conclusion: don't install symfony/event-dispatcher v4.2.4
    - bigperson/modulpos-php-api-client dev-master requires guzzle/guzzle ^3.9 -> satisfiable by guzzle/guzzle[3.9.x-dev, v3.9.0, v3.9.1, v3.9.2, v3.9.3].
    - guzzle/guzzle 3.9.x-dev requires symfony/event-dispatcher ~2.1 -> satisfiable by symfony/event-dispatcher[2.1.x-dev, 2.2.x-dev, 2.3.x-dev, 2.4.x-dev, 2.5.x-dev, 2.6.x-dev, 2.7.x-dev, 2.8.x-dev, v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.38, v2.3.39, v2.3.4, v2.3.40, v2.3.41, v2.3.42, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.0-BETA1, v2.4.0-BETA2, v2.4.0-RC1, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.0-BETA1, v2.5.0-BETA2, v2.5.0-RC1, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.0-BETA1, v2.6.0-BETA2, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7,..........

**Comment by igortsev** [comment]
Resolve add to dependency  "guzzle/guzzle": "^3.9" at main composer.json

`- Updating symfony/event-dispatcher (v4.2.4 => v2.8.49):  Checking out a77e974a5f
  - Installing guzzle/guzzle (v3.9.3): Downloading (100%)    `

**Comment by igortsev** [comment]
Deprecated package guzzlehttp/guzzle migrate guzzlehttp/guzzle

**Comment by bigperson** [comment]
@igortsev guzzle требует более старую версию symfony/event-dispatcher, думаю стоит обновить guzzle в зависимостях. Буду признателен если отправите pull request

**Comment by igortsev** [comment]
@bigperson Сделаю на неделе, как до кассы доберусь.

**Comment by bigperson** [comment]
исправлено в новой версии #da8016b7e42d5e2514065865abd13d4afe808982
